[package]
name = "slog-loggly"
version = "0.2.1"
authors = ["Angelcam, Inc."]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/angelcam/rust-slog-loggly"
documentation = "https://docs.rs/slog-loggly"
homepage = "https://github.com/angelcam/rust-slog-loggly"
description = """
This is an unofficial Loggly drain for the slog logging infrastructure in Rust.
"""
categories = ["development-tools::debugging"]
keywords = ["logging", "slog", "loggly"]

[dependencies]
bytes      = "0.4.6"
futures    = "0.1.19"
hyper      = "0.11.24"
hyper-tls  = "0.1.3"
serde      = "1.0.37"
serde_json = "1.0.13"
slog       = "2.2.3"
tokio-core = "0.1.16"
