[package]
name = "slog-loggly"
version = "0.1.1"
authors = ["Ondrej Perutka <ondrej.perutka@angelcam.com>"]

[dependencies]
bytes      = "0.4.6"
futures    = "0.1.19"
hyper      = "0.11.24"
hyper-tls  = "0.1.3"
serde      = "1.0.37"
serde_json = "1.0.13"
slog       = "2.2.3"
tokio-core = "0.1.16"
