name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Check lints
        run: cargo clippy --all-features -- -D warnings
      - name: Build & test
        run: cargo test --all-features
